SENSOR_LOCATION_NAME: "YOUR SENSOR NAME"
MINUTES_BETWEEN_READS: 10

AZURE:
  IOT_CONN_STR: "{Your IoT hub device connection string}"
  MSG_TXT: '{{"location": {location},"system_time": {system_time},"cpu_temperature", {cpu_temp},"temperature": {temperature},"humidity": {humidity}}'